#   Copyright (C) 2020 Presidenza del Consiglio dei Ministri.
#   Please refer to the AUTHORS file for more information.
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU Affero General Public License for more details.
#   You should have received a copy of the GNU Affero General Public License
#   along with this program. If not, see <https://www.gnu.org/licenses/>.

from immuni_common.sanic import create_app, run_app
from immuni_otp.apis import otp
from immuni_otp.core.managers import managers

sanic_app = create_app(
    api_title="OTP Service",
    api_description="The OTP Service provides an API to the National Healthcare Service for "
    "authorising OTPs that can be used to upload data from the Mobile Client via the Exposure "
    "Ingestion Service."
    "The OTP is generated by the App and communicated by the user to the Healthcare Operator "
    "(e.g., during a phone call). "
    "The Healthcare Operator inserts the OTP into the HIS, which then registers the OTP on the "
    "OTP Service."
    "<br><br>"
    "The OTP automatically expires after a defined interval. "
    "If the data has not been uploaded by the time the OTP expires, the user will have to start "
    "the process from the beginning with a new OTP.",
    blueprints=(otp.bp,),
    managers=managers,
)

if __name__ == "__main__":  # pragma: no cover
    run_app(sanic_app)
